// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uozinnkjvydnrgvzutwp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVvemlubmtqdnlkbnJndnp1dHdwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkxNjk1NDUsImV4cCI6MjA2NDc0NTU0NX0.G0JqH9sqraF-d1nLsL7QzXQ6EcPGDpmUIrORDymXK5g";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);